'use server';
import { Geist, Geist_Mono } from 'next/font/google';
import Link from 'next/link';
import { auth } from '@/auth';
import { logoutAction } from './logout/action';
import 'bootstrap/dist/css/bootstrap.min.css';

// import './globals.css';
import NavItems from '../components/Nav/Nav.jsx';
// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default async function RootLayout({ children }) {
  const session = await auth();
  // console.log('layout session', session.user.name);
  return (
    <html lang='en'>
      <body>
        <header>
          <div className='container pt-3 pb-3'>
            <nav>
              <Link href='/'>Home</Link>
              {session?.user ? (
                <>
                  <span className='ms-3 me-3'>Hello, {session.user.email}</span>
                  <Link href='/bookmarks'>Bookmarks</Link>
                  <Link href='/dashboard'>Dashboard</Link>
                  <form action={logoutAction} method='post' className='ms-auto'>
                    <button className='btn btn-danger ' type='submit'>
                      Logout
                    </button>
                  </form>
                </>
              ) : (
                <>
                  <Link className='ms-3' href='/login'>
                    Login
                  </Link>
                  <Link className='ms-3' href='/register'>
                    Register
                  </Link>
                </>
              )}
            </nav>
          </div>
        </header>
        {/* <NavItems /> */}
        {children}
      </body>
    </html>
  );
}
