'use server';
import { auth } from '@/auth';
import { logoutAction } from './logout/action';

import 'bootstrap/dist/css/bootstrap.min.css';
import NavItems from '@/components/Nav/Nav.jsx';
import ToastFromQuery from '@/components/ToastFromQuery/ToastFromQuery.jsx';
import { Toaster } from 'react-hot-toast';

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default async function RootLayout({ children }) {
  const session = await auth();
  return (
    <html lang='en'>
      <body>
        <header>
          <NavItems session={session} logoutAction={logoutAction} />
        </header>
        {children}
        <ToastFromQuery />
        <Toaster position='top-right' />
      </body>
    </html>
  );
}
